### ISSUE TITLE
Reverse gear doesn't work

### ISSUE THREAD

**Issue by Maogami** [Mogli12/GearboxAddon#194]
Hey, I'm having problems with reverse gear. Problem occurs either with mods like MR / Seasons and without them. Namely when I try to reverse (like I always do: clutch and move hshifter to designated position) nothing happens. Yes, i am using a G27 wheel and gear shifter combo and yes the shifter is working fine in every other game. I'm using latest release github. 
![image](https://user-images.githubusercontent.com/28206886/28935488-014f3f66-7885-11e7-97c6-284a5deaf1d0.png)

**Comment by BlaggyXD** [comment]
Hello,
there was some body befor you that said the same in German and i could help him so mabye i also can help you. His problem was that he tought he had a reverse gear but he had a reverse group, you need to shift in to the 7Th gear ( button 15) and then shift againe in to a gear. But it looks like you havent even mapped the shuttle it should be : "Gearbox: Rewers" but i am not 100% sure because i dont know any Polskan, try to set the reversegear of youre shifter to that and then it should be fixed.

Greets,
Blaggy

**Comment by Maogami** [comment]
Gonna try it in a sec.

and btw nice try with Polskan xD it should be something like Polski if you mean language : P

**Comment by Mogli12** [comment]
If the reverse is shifted in the ranges you still need the G27 gear shifter to select the "right" gear.
