### ISSUE TITLE
The helper turns off the engine but the engine is running.

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#201]
While playing the MP, only at the client when the helper has finished, HUD appears in the message that the engine is off, but can hear the game as the engine is running and you see smoke but you can not drive. You have to press the ignition key 2 times to start the engine, the first press turns off the engine and the second starts.

**Comment by KITT3000** [comment]
The problem still occurs, but now only when I am in the vehicle while the helper is working. When the helper finishes work, HUD displays "engine off", but you hear the engine running and you see smoke. You must turn off the engine yourself and turn it on again to be able to drive. The problem no longer occurs when I turn on the helper and leave it alone to finish the job, then turns off the engine properly.

**Comment by Mogli12** [comment]
Hmm, the gearbox does not turn off the transmission if the hired worked finished. The display of "engine off" is based on the standard field self.isMotorStarted. But what you described seems to be a mismatch between self.isMotorStarted and sounds etc. So I fear that this problem is cause by another mod.

**Comment by KITT3000** [comment]
You were right, I checked several mods that could interfere with this variable and I found the culprit: GameExtension.
Thanks for the reply and I apologize for the trouble ;)
