### ISSUE TITLE
30232II keep range/gear in auto mode

### ISSUE THREAD

**Issue by ivanlii** [Mogli12/GearboxAddon#285]
Hi Mogli, with new changes to cruise control, what to change to keep same range/gear in automode for longer time(rpm) intreval?

test: only GB, sosnovka, field 3, Challenger MT800, Lemken Titan11, cruise control10km/h, automatic =>
keep switching gears 11(1580rpm) and 12(1410rpm).
With more mods like grounresponse or mr is worse.
edit: 30231 working perfect
Thank you

**Comment by Mogli12** [comment]
Hi ivanlii,

You can turn off the automatic with gearboxMogliAUTOMATIC (KEY_rctrl KEY_slash) or in the settings dialog. I think that with the power consumption with a plough is totally unrealistic even with moreRealistic. If you slow down by just one km/h the power consumption reduced by 50%. That's why the target RPM is somewhere between 1410 and 1580 RPM.

Regards, Stefan

**Comment by ivanlii** [comment]
Thanx Stefan, i will try other tractors and if it is same problem i will stay with 231 for a while.

**Comment by Mogli12** [comment]
As I already wrote before: it is very quick to turn off automatic with KEY_rctrl KEY_slash. Or you go to the settings and increase the min target RPM.

**Comment by ivanlii** [comment]
2.3.0.2:
crazy jumping between gears has stopped! 
thank you Stefan!
