### ISSUE TITLE
clutchRatio and more

### ISSUE THREAD

**Issue by mrPassion78** [Mogli12/GearboxAddon#401]
Hi Stefan, 
could you maybe tell me what the flowing things mean:
ClutchRatio="1"
minClutchRatio="0.3" 
maxClutchRatio="0.95"

I see that in every gearbox, but not sure what it means..
I think The Min and Max, are that it will allow to shift before and/or after the set speed for the gear that it is in at that time?. 

and i found 1 more i have no idea what it does: 
<ranges defaultRange="2" shiftTimeMs="1500" gearOffset="2">
That gearOffset, no idea what that does or refers to.

I really like to get the hang of it, to make the conversions the best i can and gearbox makes it 100 times better. 
so thanx for this mod.

greetings Pascal

**Comment by Mogli12** [comment]
Hi Pascal,

maxClutchRatio="0.95" means that the clutch does not fully close. So it behaves like a Voith turbo clutch or a torque converter. I propose not to use it directly and to replace it by attribute `torqueConverterProfile` with values **"wheelLoader"**, **"clutch"**, **"oldCar"** and **"modernCar"**.

So left me first explain, what `clutchRatio`(**C**) means. It goes back to the clutch in moreRealistic in FS13. Based on the RPMs of your wheel and the gear ratio you have a certain rotation speed coming from your transmission. Let's call it `wheelRpm` or short **W**. The motor rotates at `motorRpm` or short **M**. The position of the acceleration pedal corresponds to a certain RPM the motor would rotate at in neutral. This is the `throttleRpm` (**T**). Now the motorRpm is calculated with the following formula:
```
M = C * W + (1-C) * T
```
So the clutch ratio is the ratio of how much influence the wheel RPM has on the motor RPM. `clutchRatio=0` means that there is no connection between wheels and motor, the clutch is open. `clutchRatio=1`means that there is a static connection between wheels and motor, the clutch is fully closed.

Now let's look at `clutchRatio=0.95`. Depending on the position of the acceleration pedal the throttleRpm is between 900 and 2200 RPM. Gear ratio and rotation speed of the wheels would lead to `wheelRpm=1600`. So the `motorRpm` would be between 
```
M = 0.95 * 1600 + 0.05 * 900 =  1565
```
and
```
M = 0.95 * 1600 +  0.05 * 2200 = 1630
```
This would simulate a turbo clutch or torque converter fully filled with oil. The defaults for such clutches are `minClutchPercent="0.2" maxClutchPercent="0.96". Additionally, there are the attributes `torqueConverterMaxFactor` (defaults 1.25 for profile **"clutch"**, 3.2 otherwise) and `torqueConverterLockupMs` (default 200 if the vehicle has a converter lockup clutch, Wandlerüberrückungskupplung in German).

It hope this explains it a little.

Regards,
Stefan 

-

**Comment by mrPassion78** [comment]
Hi Stefan, 
Thanks very very much for this extensive explanation, this makes a lot of sense, and i actually understand really good what you explained..
I now now, what files to use instead, and how to read the whole thing.. 
Thanx a lot .

sincerely Pascal.
