### ISSUE TITLE
concerns about fuel consumption

### ISSUE THREAD

**Issue by Dudejo** [Mogli12/GearboxAddon#424]
Is it possible that fuel consumption could be calculated without taking engine torque into account?

It causes weird behavior with low torque engines (like the Rodeo) as they consume ludicrously low amounts of fuel. In the Rodeo's case, I had to double the fuelUsageRatio for it to get the realistic ~20 mpg it typically achieves in real life.

**Comment by Mogli12** [comment]
Hi,
The fuel consumption is calculated based on the used torque (from Giants engine) and the specific fuel consumption (g/kWh). I assume that Giants engine is optimized for slow and heavy vehicles and the Rodeo is light and fast compared to a tractor. If you would use moreRealistic it would at least try to simulate drag.
Regards,
Stefan

**Comment by Mogli12** [comment]
Ah, I forgot. The motor load is considered as well. The best efficiency is at 80% load. So at 60% load or at 100% load more fuel is consumed.

**Comment by Dudejo** [comment]
I did not know that about motor load.

However...that's not quite what my issue is. The best way I can explain it is that as the engine goes through its RPM range, weaker torque values on the torque curve act as if the engine is deliberately preventing fuel+air from entering the cylinders.

In my previous motor template tests, fuel consumption increased linearly with torque output regardless of any other factors.

With that in mind, I think it would be logical to amend fuelUsageRatio calculations to counteract this behavior.

**Comment by Dudejo** [comment]
I made this picture that hopefully clears up what I'm trying to convey

https://cdn.discordapp.com/attachments/412348931473801217/499042411280990208/example.png

**Comment by Mogli12** [comment]
Hi,

The fuel consumption rate is the is value at 80% load. Please check for example this article: https://en.wikipedia.org/wiki/Consumption_map and look at the values at 80% of the red line.

The gearbox addon uses these values and multiplies it with RPM, torque, a factory derived from the ratio between used and available torque and a conversion factor.

Regards,
Stefan

**Comment by Dudejo** [comment]
When you say torque, what exactly does that mean?

Torque @ RPM? What if the engine is being run outside of the turbo's boost threshold (The RPM at which the turbo has enough airflow to run at peak boost)?

Generally, turbo engines make very little power under the boost threshold. With the way fuel consumption works in your mod, running the engine at those RPMs would provide the best fuel economy. The consumption drops so low, even at maximum load, that it's more economical than a Smart Fortwo.

**Comment by Mogli12** [comment]
Torque means that torque the the vehicle currently uses. It is calculated within Giants engine. Since the fuelUsageRatio is at 80% load, this value is compared with the available torque the the same RPM. That is the ratio. The values are:
- 0% load => factor 10
- 2% load => factor 8
- 20% load => factor 2
- 60% load => factor 1.05
- 80% load => factor 1
- 90% load => factor 1.02
- 100% load => factor 1.1

A turbo lag would lead to little torque compared to available torque and thus to a high factor. But gearbox addon does not simulate turbo lag.

Regards,
Stefan

**Comment by Dudejo** [comment]
Turbo lag is not the same as boost threshold. Turbo lag is just the time it takes for the turbine to change its own RPM. Even belt-driven turbos (aka superchargers) have a boost threshold.

And yeah, if torque, in this context, means whatever is used by the vehicle... if I'm running a simulated 15 liter truck engine at, say, 350 RPM where it can only "use" up to 100 nm of torque, it will consume so little fuel that it will counteract whatever penalties exist in the system, such as the factor 10 for low engine load or the higher fuelUsageRatio such low RPMs typically have.

And so, you end up with 20 ton tractors wit better fuel efficiency than a 3-cylinder 2-seat town car.

**Comment by Dudejo** [comment]
The problem is not rpm. It's never been about rpm.

The problem is that fuel consumption is being directly influenced by how much torque the vehicle is using.

The intended engine could be a 30 liter mining truck but if the torque curve limits the engine to 100 nm for any reason, fuel consumption will reflect a much smaller platform

Sent from my iPod

On 2018-10-12, at 3:25 PM, "Stefan Biedenstein" <notifications@github.com<mailto:notifications@github.com>> wrote:


If you want higher fuel consumption at low RPM why don't you just increase that values at low RPM. There is anyhow not much known about specific fuel consumption at RPM below max. torque RPM.

**Comment by Mogli12** [comment]
The engine has a specific fuel consumption (e.g. in g per kWh). If you multiply torque by RPM and divide it by the right constant you get power in kW. 

And yes, at constant (used) torque and RPM the engine uses least fuel at about 80% load at lowest RPM somewhere above 1100 RPM.

Your problem is that Giants program does not take all forces into account. This is a simulation of tractors. It does not care about drag and I guess to simulation of rolling resistance focuses on rolling resistance on a field, not on road.

So I guess that the calculation of used torque is not good at higher speed on a road.

**Comment by Mogli12** [comment]
https://www.youtube.com/watch?v=iNspNdVkslA
