### ISSUE TITLE
assign transmission config to tractor

### ISSUE THREAD

**Issue by vinatron** [Mogli12/GearboxAddon#83]
how to I change the transmission of a tractor from one type to another. In other words, from hydrostatic to manual shift?

**Comment by Mogli12** [comment]
If you create your own gearboxAddonConfig.xml directly in the mods folder you can overwrite the settings with your own values.

**Comment by vinatron** [comment]
I understand. One more question, how would you encode a mod for something like a torque amplifier? This would be for a Farmall 300 with a 5 speed gear transmission and a torque amplifier between the engine and the transmission input shaft.

**Comment by Mogli12** [comment]
Hi, there are several parameters and most of them are not yet well documented. Maybe you check the CaseIH 1455 first:
https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon/gearboxAddonConfig.xml

The gearboxMogli tag has the following attributes:
`<gearboxMogli autoStartStop="false" maxAIRange="1" rpmInSpeedHud="true" torqueConverterMaxFactor="1.25" torqueConverter="true" minClutchRatio="0.6">`

Most important is `torqueConverter="true"`. Since the case just has a "turbo clutch" but no "torque converter" I restricted `torqueConverterMaxFactor="1.25"`. You can play around with `minClutchRatio="0.6"`. This means that at full throttle (rated RPM 2100) and at 0 km/h the engine will rev at 0.6*0+(1-0.6)*2100 = 840. So it is quite stiff.

If you want to lock/bridge the torque converter at certain RPMs you can use `clutchCloseRpm` and `clutchOpenRpm`.

**Comment by vinatron** [comment]
Mogli12, 
Thanks for the help. I went in and added code to make what I thought would be a torque amplifier or "high-low" range coupler between the engine and transmission but couldn't get it to work. Some of the tractors I used to run a long time ago had them such as the Farmall-M T/A. It was the same as the standard "M" but had a lever to work the planetary gear set in between the engine clutch and transmission input shaft. You could engage/disengage the TA lever on-the-go. The only drawback was that in "high" you had no engine braking going down hill. Anyway, this is what I am trying to add to my gearbox mod but it keeps messing up. Now all my tractors are burning out the clutch at 57% torque input or "engagement".  I can't seem to find where the error is.  Is there a tutorial somewhere that can tell me what the syntax is for encoding? I am changing numerical values without fully understanding what to expect. Trial and error is very time consuming, since you have to reboot the simulator every time you make a change. You have been generous with your time but sooner or later I have to learn the language. Appreciate any advice you have.

**Comment by Mogli12** [comment]
Ah, I think you mean something different with torque amplifier. This is like a 2 gear power shift, right? Please check the Zetor 12045 in the config XML.
